/*
 * Copyright (c) 2020 WildFireChat. All rights reserved.
 */

import ChannelMenu from "./channelMenu.uts";
import { redirectMediaUrl } from '../../common/mediaUrlRedirector.uts'

export default class ChannelInfo {
    channelId = '';
    name = '';
    portrait = '';
    desc = '';
    owner = '';
    // 0, public; 1, private; 2, destoryed
    status = 0;
    extra = '';
    updateDt = 0;
    menus: ChannelMenu[] = [];

    // ---- UI 层补丁字段 ----
    _displayName = '';

    //第0位表示是否允许查看用户所有信息，还是只允许看用户id，用户名称，用户昵称和用户头像
    static StatusMaskFullInfo = 0x01;
    //第1位表示是否允许查看非订阅用户信息
    static StatusMaskUnsubscribedUserAccess = 0x02;
    //第2位表示是否允许主动添加用户订阅关系
    static StatusMaskActiveSubscribe = 0x04;
    //第3位表示是否允许给非订阅用户发送消息
    static StatusMaskMessageUnsubscribed = 0x08;
    //第4位表示是否私有
    static StatusMaskPrivate = 0x10;
    //第6位表示是否删除
    static StatusMaskDeleted = 0x40;
    //第8位表示是否全局频道，全局平道发送消息时，会广播给系统所有人
    static StatusMaskGlobal = 0x80;

    static fromJsonObject(obj: UTSJSONObject): ChannelInfo {
        const c = new ChannelInfo()
        c.channelId = obj.getString('channelId') ?? ''
        c.name = obj.getString('name') ?? ''
        c.portrait = redirectMediaUrl(obj.getString('portrait') ?? '')
        c.desc = obj.getString('desc') ?? ''
        c.owner = obj.getString('owner') ?? ''
        c.status = obj.getNumber('status') ?? 0
        c.extra = obj.getString('extra') ?? ''
        c.updateDt = obj.getNumber('updateDt') ?? 0
        const menuArr = obj.getArray<UTSJSONObject>('menus')
        if (menuArr != null) {
            for (let i = 0; i < menuArr.length; i++) {
                c.menus.push(ChannelMenu.fromJsonObject(menuArr[i]))
            }
        }
        return c
    }
}
