/*
 * Copyright (c) 2020 WildFireChat. All rights reserved.
 */
import { redirectMediaUrl } from '../../common/mediaUrlRedirector.uts'

export default class ChatRoomInfo {
    chatRoomId = '';
    title = '';
    desc = '';
    portrait = '';
    extra = '';
    // 0, normal; 1, not start; 2, end
    state = 0;
    memberCount = 0;
    createDt = 0;
    updateDt = 0;

    static fromJsonObject(obj: UTSJSONObject): ChatRoomInfo {
        const c = new ChatRoomInfo()
        c.chatRoomId = obj.getString('chatRoomId') ?? ''
        c.title = obj.getString('title') ?? ''
        c.desc = obj.getString('desc') ?? ''
        c.portrait = redirectMediaUrl(obj.getString('portrait') ?? '')
        c.extra = obj.getString('extra') ?? ''
        c.state = obj.getNumber('state') ?? 0
        c.memberCount = obj.getNumber('memberCount') ?? 0
        c.createDt = obj.getNumber('createDt') ?? 0
        c.updateDt = obj.getNumber('updateDt') ?? 0
        return c
    }
}
