/*
 * Copyright (c) 2020 WildFireChat. All rights reserved.
 */

import UserInfo from "./userInfo.uts";

export default class FriendRequest {
    direction = 0;
    target = '';
    reason = '';
    extra = '';
    //    RequestStatus_Sent = 0,
    //    RequestStatus_Accepted = 1,
    //    RequestStatus_Rejected = 3
    status = 0;
    readStatus = 0;
    timestamp = 0;

    // ---- UI 层补丁字段 ----
    _target: UserInfo | null = null;

    static fromJsonObject(obj: UTSJSONObject): FriendRequest {
        const fr = new FriendRequest()
        fr.direction = obj.getNumber('direction') ?? 0
        fr.target = obj.getString('target') ?? ''
        fr.reason = obj.getString('reason') ?? ''
        fr.extra = obj.getString('extra') ?? ''
        fr.status = obj.getNumber('status') ?? 0
        fr.readStatus = obj.getNumber('readStatus') ?? 0
        fr.timestamp = obj.getNumber('timestamp') ?? 0
        return fr
    }
}
