/*
 * Copyright (c) 2020 WildFireChat. All rights reserved.
 */

import GroupType from "./groupType.uts";
import { redirectMediaUrl } from '../../common/mediaUrlRedirector.uts'

export default class GroupInfo {
    target = '';
    name = '';
    portrait = '';
    owner = '';
    type: number = GroupType.Normal;
    memberCount = 0;
    extra = '';
    remark = '';
    updateDt = 0;
    deleted = 0;
    memberDt = 0;

    //0 正常；1 全局禁言
    mute = 0;

    //在group type为Restricted时，0 开放加入权限（群成员可以拉人，用户也可以主动加入）；1 只能群成员拉人入群；2 只能群管理拉人入群
    joinType = 0;

    //是否运行群中普通成员私聊。0 允许，1不允许
    privateChat = 0;

    //是否是超级群组
    superGroup = 0;

    //是否可以搜索到该群，功能暂未实现
    searchable = 0;

    //是否可以查看群历史消息, 0 不允许，1允许。仅专业版有效
    historyMessage = 0;

    //群最大成员数。仅专业版有效
    maxMemberCount = 0;

    // ---- UI 层补丁字段 ----
    _isFav = false;

    static fromJsonObject(obj: UTSJSONObject): GroupInfo {
        const g = new GroupInfo()
        g.target = obj.getString('target') ?? ''
        g.name = obj.getString('name') ?? ''
        g.portrait = redirectMediaUrl(obj.getString('portrait') ?? '')
        g.owner = obj.getString('owner') ?? ''
        g.type = obj.getNumber('type') ?? GroupType.Normal
        g.memberCount = obj.getNumber('memberCount') ?? 0
        g.extra = obj.getString('extra') ?? ''
        g.remark = obj.getString('remark') ?? ''
        g.updateDt = obj.getNumber('updateDt') ?? 0
        g.deleted = obj.getNumber('deleted') ?? 0
        g.memberDt = obj.getNumber('memberDt') ?? 0
        g.mute = obj.getNumber('mute') ?? 0
        g.joinType = obj.getNumber('joinType') ?? 0
        g.privateChat = obj.getNumber('privateChat') ?? 0
        g.superGroup = obj.getNumber('superGroup') ?? 0
        g.searchable = obj.getNumber('searchable') ?? 0
        g.historyMessage = obj.getNumber('historyMessage') ?? 0
        g.maxMemberCount = obj.getNumber('maxMemberCount') ?? 0
        return g
    }
}
