/*
 * Copyright (c) 2020 WildFireChat. All rights reserved.
 */

export default class UnreadCount {
    // 单聊未读数
    unread = 0;
    // 群聊@数
    unreadMention = 0;
    // 群聊@All数
    unreadMentionAll = 0;

    static fromJsonObject(obj: UTSJSONObject | null): UnreadCount {
        const uc = new UnreadCount()
        if (obj != null) {
            uc.unread = obj.getNumber('unread') ?? 0
            uc.unreadMention = obj.getNumber('unreadMention') ?? 0
            uc.unreadMentionAll = obj.getNumber('unreadMentionAll') ?? 0
        }
        return uc
    }
}
