/*
 * Copyright (c) 2020 WildFireChat. All rights reserved.
 */

import UserCustomState from "./userCustomState.uts";
import UserClientState from "./userClientState.uts";

export default class UserOnlineState {
    userId = '';
    customState: UserCustomState = new UserCustomState();
    clientStates: UserClientState[] = [];

    // 手机在线、web在线、pc在线
    desc(): string {
        if (this.customState.state > 0) {
            //0，未设置，1 忙碌，2 离开（主动设置），3 离开（长时间不操作），4 隐身，其它可以自主扩展。
            const cs = ['未设置', '忙碌', '离开(主动离开)', '离开(长时间未操作)', '隐身'];
            let stateDesc = ''
            if (this.customState.state < cs.length) {
                stateDesc = cs[this.customState.state]
            }
            return this.customState.text + stateDesc;
        }

        let onlineClientDesc = '';
        let lastSeenDesc = '';
        const ps = ['', 'iOS', 'Android', 'Windows', 'mac', 'Web', '小程序', 'Linux', 'iPad', 'Android-Pad', 'Harmony', 'Harmony-Pad', 'Harmony-PC'];
        for (let i = 0; i < this.clientStates.length; i++) {
            const s = this.clientStates[i]
            if (s.platform < 0 || s.platform >= ps.length) {
                continue
            }
            if (s.state == 0) {
                onlineClientDesc += ps[s.platform] + ' '
            } else if ([1, 2, 8, 9].indexOf(s.platform) >= 0) {
                lastSeenDesc += ps[s.platform] + ' ';
            }
        }

        if (onlineClientDesc.trim() != '') {
            return onlineClientDesc + '在线';
        } else if (lastSeenDesc.trim() != '') {
            return lastSeenDesc + '不久前在线';
        }
        return '';
    }
}
