/*
 * Copyright (c) 2020 WildFireChat. All rights reserved.
 */

import { getGroupMemberDisplayName } from '../../client/userBrief.uts'
import { utf8_to_b64, b64_to_utf8 } from '../../util/base64.uts'
import MessageContentType from "../messageContentType.uts";
import MessagePayload from '../messagePayload.uts';
import GroupNotificationContent from "./groupNotification.uts";

export default class ChangeGroupNameNotification extends GroupNotificationContent {
    operator = '';
    name = '';

    constructor(operator: string, name: string) {
        super(MessageContentType.ChangeGroupName_Notification);
        this.operator = operator;
        this.name = name;
    }

    override formatNotification(message: any | null): string {
        if (this.fromSelf) {
            return '您修改群名称为：' + this.name;
        } else {
            return getGroupMemberDisplayName(this.groupId, this.operator) + '修改群名称为：' + this.name;
        }
    }

    override encode(): MessagePayload {
        const payload = super.encode();
        const obj = {
            g: this.groupId,
            n: this.name,
            o: this.operator,
        } as UTSJSONObject;
        payload.binaryContent = utf8_to_b64(JSON.stringify(obj)!);
        return payload;
    }

    override decode(payload: MessagePayload): void {
        super.decode(payload);
        const obj = JSON.parseObject(b64_to_utf8(payload.binaryContent));
        if (obj != null) {
            this.groupId = obj.getString('g') ?? '';
            this.operator = obj.getString('o') ?? '';
            this.name = obj.getString('n') ?? '';
        }
    }
}
