/*
 * Copyright (c) 2022 WildFireChat. All rights reserved.
 */

import NotificationMessageContent from "./notificationMessageContent.uts";
import MessageContentType from "../messageContentType.uts";

export default class FriendGreetingNotification extends NotificationMessageContent {
    constructor() {
        super(MessageContentType.Friend_Greeting);
    }

    override formatNotification(message: any | null): string {
        return "以上是打招呼的内容";
    }
}
