/*
 * Copyright (c) 2020 WildFireChat. All rights reserved.
 */

import NotificationMessageContent from "./notificationMessageContent.uts";
import MessageContentType from "../messageContentType.uts";

export default class FriendAddedNotification extends NotificationMessageContent {
    constructor() {
        super(MessageContentType.Friend_Added);
    }

    override formatNotification(message: any | null): string {
        return "你们已经是好友了，可以开始聊天了。";
    }
}
