/*
 * Copyright (c) 2020 WildFireChat. All rights reserved.
 */

import GroupNotificationContent from "./groupNotification.uts";
import { getGroupMemberDisplayName } from '../../client/userBrief.uts'
import { utf8_to_b64, b64_to_utf8 } from '../../util/base64.uts'
import MessageContentType from "../messageContentType.uts";
import MessagePayload from '../messagePayload.uts';

export default class GroupJoinTypeNotificationContent extends GroupNotificationContent {
    operator = '';

    //在group type为Restricted时，0 开放加入权限（群成员可以拉人，用户也可以主动加入）；1 只能群成员拉人入群；2 只能群管理拉人入群
    joinType = 0;

    constructor(operator: string, joinType: number) {
        super(MessageContentType.ChangeJoinType_Notification);
        this.operator = operator;
        this.joinType = joinType;
    }

    override formatNotification(message: any | null): string {
        let notifyStr: string;
        if (this.fromSelf) {
            notifyStr = '您';
        } else {
            notifyStr = getGroupMemberDisplayName(this.groupId, this.operator);
        }
        switch (this.joinType) {
            case 0:
                notifyStr += ' 开放了加入群组功能';
                break;
            case 1:
                notifyStr += ' 仅允许群成员邀请加入群组';
                break;
            case 2:
                notifyStr += " 关闭了加入群组功能";
                break;
            default:
                break;
        }
        return notifyStr;
    }

    override encode(): MessagePayload {
        const payload = super.encode();
        const obj = {
            g: this.groupId,
            o: this.operator,
            n: (this.joinType.toString())
        } as UTSJSONObject;
        payload.binaryContent = utf8_to_b64(JSON.stringify(obj)!);
        return payload;
    }

    override decode(payload: MessagePayload): void {
        super.decode(payload);
        const obj = JSON.parseObject(b64_to_utf8(payload.binaryContent));
        if (obj != null) {
            this.groupId = obj.getString('g') ?? '';
            this.operator = obj.getString('o') ?? '';
            this.joinType = parseInt(obj.getString('n') ?? '0');
        }
    }
}
