/*
 * Copyright (c) 2020 WildFireChat. All rights reserved.
 */

import GroupNotificationContent from "./groupNotification.uts";
import MessageContentType from "../messageContentType.uts";
import { getGroupMemberDisplayName } from '../../client/userBrief.uts'
import { utf8_to_b64, b64_to_utf8 } from '../../util/base64.uts'
import MessagePayload from '../messagePayload.uts';

export default class GroupSetManagerNotificationContent extends GroupNotificationContent {
    operator = '';
    // 1, 设置为管理员；0，取消管理员
    setManagerType = 0;
    memberIds: string[] = [];

    constructor(operator: string, setManagerType: number, memberIds: string[]) {
        super(MessageContentType.SetGroupManager_Notification);
        this.operator = operator;
        this.setManagerType = setManagerType;
        this.memberIds = memberIds;
    }

    override formatNotification(message: any | null): string {
        let notifyStr = this.fromSelf ? '您' : getGroupMemberDisplayName(this.groupId, this.operator)
        notifyStr += '把 ';
        for (let i = 0; i < this.memberIds.length; i++) {
            notifyStr += ' ';
            notifyStr += getGroupMemberDisplayName(this.groupId, this.memberIds[i]);
        }
        notifyStr += ' ';
        notifyStr += this.setManagerType == 0 ? '取消了管理员' : '设置为了管理员';
        return notifyStr;
    }

    override encode(): MessagePayload {
        const payload = super.encode();
        const obj = {
            g: this.groupId,
            o: this.operator,
            n: this.setManagerType.toString(),
            ms: this.memberIds,
        } as UTSJSONObject;
        payload.binaryContent = utf8_to_b64(JSON.stringify(obj)!);
        return payload;
    }

    override decode(payload: MessagePayload): void {
        super.decode(payload);
        const obj = JSON.parseObject(b64_to_utf8(payload.binaryContent));
        if (obj != null) {
            this.groupId = obj.getString('g') ?? '';
            this.operator = obj.getString('o') ?? '';
            this.setManagerType = parseInt(obj.getString('n') ?? '0');
            this.memberIds = obj.getArray<string>('ms') ?? ([] as string[]);
        }
    }
}
