/*
 * Copyright (c) 2020 WildFireChat. All rights reserved.
 */

import { getGroupMemberDisplayName } from '../../client/userBrief.uts'
import { utf8_to_b64, b64_to_utf8 } from '../../util/base64.uts'
import MessageContentType from '../messageContentType.uts';
import MessagePayload from '../messagePayload.uts';
import GroupNotificationContent from './groupNotification.uts';

export default class QuitGroupNotification extends GroupNotificationContent {
    operator = '';

    constructor(op: string) {
        super(MessageContentType.QuitGroup_Notification);
        this.operator = op;
    }

    override formatNotification(message: any | null): string {
        if (this.fromSelf) {
            return '您退出了群组';
        } else {
            return getGroupMemberDisplayName(this.groupId, this.operator) + '退出了群组';
        }
    }

    override encode(): MessagePayload {
        const payload = super.encode();
        const obj = {
            g: this.groupId,
            o: this.operator,
        } as UTSJSONObject;
        payload.binaryContent = utf8_to_b64(JSON.stringify(obj)!);
        return payload;
    }

    override decode(payload: MessagePayload): void {
        super.decode(payload);
        const obj = JSON.parseObject(b64_to_utf8(payload.binaryContent));
        if (obj != null) {
            this.groupId = obj.getString('g') ?? '';
            this.operator = obj.getString('o') ?? '';
        }
    }
}
