/*
 * Copyright (c) 2020 WildFireChat. All rights reserved.
 */

import NotificationMessageContent from './notificationMessageContent.uts'
import MessageContentType from "../messageContentType.uts";
import MessagePayload from '../messagePayload.uts';

export default class StartSecretChatNotification extends NotificationMessageContent {
    constructor() {
        super(MessageContentType.StartSecretChat_Notification);
    }

    override formatNotification(message: any | null): string {
        // 密聊功能移动端 uni 版本未实现
        return "密聊会话";
    }

    override encode(): MessagePayload {
        return super.encode();
    }

    override decode(payload: MessagePayload): void {
        super.decode(payload);
    }
}
