/*
 * Copyright (c) 2020 WildFireChat. All rights reserved.
 */

import NotificationMessageContent from './notificationMessageContent.uts'
import MessagePayload from '../messagePayload.uts';

export default class TemplateNotification extends NotificationMessageContent {
    tip = '';

    constructor(type: number) {
        super(type)
        this.tip = '';
    }

    override formatNotification(message: any | null): string {
        return this.tip;
    }

    override digest(message: any | null): string {
        return this.tip;
    }

    override encode(): MessagePayload {
        const payload = super.encode();
        payload.content = this.tip;
        return payload;
    }

    override decode(payload: MessagePayload): void {
        super.decode(payload);
        this.tip = payload.content;
    }
}
