/*
 * Copyright (c) 2020 WildFireChat. All rights reserved.
 */

import { getGroupMemberDisplayName } from '../../client/userBrief.uts'
import { utf8_to_b64, b64_to_utf8 } from '../../util/base64.uts'
import MessageContentType from '../messageContentType.uts';
import MessagePayload from '../messagePayload.uts';
import GroupNotificationContent from './groupNotification.uts';

export default class TransferGroupOwnerNotification extends GroupNotificationContent {
    operator = '';
    newOwner = '';

    constructor(operator: string, newOwner: string) {
        super(MessageContentType.TransferGroupOwner_Notification);
        this.operator = operator;
        this.newOwner = newOwner;
    }

    override formatNotification(message: any | null): string {
        if (this.fromSelf) {
            return '您把群转让给了 ' + getGroupMemberDisplayName(this.groupId, this.newOwner);
        } else {
            return getGroupMemberDisplayName(this.groupId, this.operator) + '把群转让给了 ' + getGroupMemberDisplayName(this.groupId, this.newOwner)
        }
    }

    override encode(): MessagePayload {
        const payload = super.encode();
        const obj = {
            g: this.groupId,
            o: this.operator,
            m: this.newOwner,
        } as UTSJSONObject;
        payload.binaryContent = utf8_to_b64(JSON.stringify(obj)!);
        return payload;
    }

    override decode(payload: MessagePayload): void {
        super.decode(payload);
        const obj = JSON.parseObject(b64_to_utf8(payload.binaryContent));
        if (obj != null) {
            this.groupId = obj.getString('g') ?? '';
            this.operator = obj.getString('o') ?? '';
            this.newOwner = obj.getString('m') ?? '';
        }
    }
}
