import MessageContent from '../../messages/messageContent.uts';
import MessageContentType from '../../messages/messageContentType.uts';
import MessagePayload from '../../messages/messagePayload.uts';
import { utf8_to_b64, b64_to_utf8 } from '../../util/base64.uts'

export default class CallAnswerTMessageContent extends MessageContent {
    callId = '';
    audioOnly = false;
    inviteMessageUid = '';

    constructor() {
        super(MessageContentType.VOIP_CONTENT_TYPE_ACCEPT_T);
    }

    override digest(message: any | null): string {
        return '[通话应答]';
    }

    override encode(): MessagePayload {
        const payload = super.encode();
        payload.content = this.callId;
        const obj = { a: this.audioOnly ? 1 : 0, u: this.inviteMessageUid } as UTSJSONObject;
        payload.binaryContent = utf8_to_b64(JSON.stringify(obj)!);
        return payload;
    }

    override decode(payload: MessagePayload): void {
        super.decode(payload);
        this.callId = payload.content;
        if (payload.binaryContent != '') {
            const obj = JSON.parseObject(b64_to_utf8(payload.binaryContent));
            if (obj != null) {
                this.audioOnly = (obj.getNumber('a') ?? 0) == 1;
                this.inviteMessageUid = obj.getString('u') ?? '';
            }
        }
    }
}
