import MessageContent from '../../messages/messageContent.uts';
import MessageContentType from '../../messages/messageContentType.uts';
import MessagePayload from '../../messages/messagePayload.uts';
import { utf8_to_b64, b64_to_utf8 } from '../../util/base64.uts'

export default class CallByeMessageContent extends MessageContent {
    callId = '';
    reason = 0;
    inviteMsgUid = '';

    constructor() {
        super(MessageContentType.VOIP_CONTENT_TYPE_END);
    }

    override digest(message: any | null): string {
        return '[通话结束]';
    }

    override encode(): MessagePayload {
        const payload = super.encode();
        payload.content = this.callId;
        const obj = { r: this.reason, u: this.inviteMsgUid } as UTSJSONObject;
        payload.binaryContent = utf8_to_b64(JSON.stringify(obj)!);
        return payload;
    }

    override decode(payload: MessagePayload): void {
        super.decode(payload);
        this.callId = payload.content;
        if (payload.binaryContent != '') {
            const obj = JSON.parseObject(b64_to_utf8(payload.binaryContent));
            if (obj != null) {
                this.reason = obj.getNumber('r') ?? 0;
                this.inviteMsgUid = obj.getString('u') ?? '';
            }
        }
    }
}
