import MessageContent from "../../messages/messageContent.uts";
import MessageContentType from "../../messages/messageContentType.uts";
import MessagePayload from '../../messages/messagePayload.uts';
import { utf8_to_b64, b64_to_utf8 } from '../../util/base64.uts'

export default class ConferenceInviteMessageContent extends MessageContent {
    callId = '';
    host = '';
    title = '';
    desc = '';

    startTime = 0;
    audioOnly = false;
    audience = false;
    pin = '';
    advanced = false;

    constructor() {
        super(MessageContentType.CONFERENCE_CONTENT_TYPE_INVITE);
    }

    override digest(message: any | null): string {
        return '[会议邀请]'
    }

    override encode(): MessagePayload {
        const payload = super.encode();
        payload.content = this.callId;
        payload.pushContent = '会议邀请';
        const obj = {
            h: this.host,
            s: this.startTime,
            t: this.title,
            d: this.desc,
            audience: this.audience ? 1 : 0,
            advanced: this.advanced ? 1 : 0,
            a: this.audioOnly ? 1 : 0,
            p: this.pin,
        } as UTSJSONObject;
        payload.binaryContent = utf8_to_b64(JSON.stringify(obj)!);
        return payload;
    }

    override decode(payload: MessagePayload): void {
        super.decode(payload);
        if (payload.binaryContent != '') {
            const obj = JSON.parseObject(b64_to_utf8(payload.binaryContent));
            if (obj != null) {
                this.host = obj.getString('h') ?? '';
                this.startTime = obj.getNumber('s') ?? 0;
                this.title = obj.getString('t') ?? '';
                this.desc = obj.getString('d') ?? '';
                this.audience = (obj.getNumber('audience') ?? 0) > 0;
                this.advanced = (obj.getNumber('advanced') ?? 0) > 0;
                this.audioOnly = (obj.getNumber('a') ?? 0) > 0;
                this.pin = obj.getString('p') ?? '';
            }
        }
        this.callId = payload.content;
    }
}
