import MessageContent from '../../messages/messageContent.uts';
import MessageContentType from '../../messages/messageContentType.uts';
import MessagePayload from '../../messages/messagePayload.uts';
import { utf8_to_b64, b64_to_utf8 } from '../../util/base64.uts'

export default class JoinCallRequestMessageContent extends MessageContent {
    callId = '';
    clientId = '';

    constructor() {
        super(MessageContentType.VOIP_Join_Call_Request);
    }

    override digest(message: any | null): string {
        return '[请求加入通话]';
    }

    override encode(): MessagePayload {
        const payload = super.encode();
        payload.content = this.callId;
        const obj = { c: this.clientId } as UTSJSONObject;
        payload.binaryContent = utf8_to_b64(JSON.stringify(obj)!);
        return payload;
    }

    override decode(payload: MessagePayload): void {
        super.decode(payload);
        this.callId = payload.content;
        if (payload.binaryContent != '') {
            const obj = JSON.parseObject(b64_to_utf8(payload.binaryContent));
            if (obj != null) {
                this.clientId = obj.getString('c') ?? '';
            }
        }
    }
}
