/*
 * Copyright © 2020 WildFireChat. All rights reserved.
 */

import MessageContent from './messageContent.uts'
import MessageContentType from './messageContentType.uts'
import MessagePayload from './messagePayload.uts';
import { utf8_to_b64, b64_to_utf8 } from '../util/base64.uts'
import Config from '../../config.uts'

export default class CardMessageContent extends MessageContent {
    /**
     * 0，用户；1，群组；2，聊天室；3，频道
     */
    cardType = 0;
    target = '';
    name = '';
    displayName = '';
    portrait = '';
    from = '';

    constructor(cardType: number = 0, target: string = '', displayName: string = '', portrait: string = '', from: string = '') {
        super(MessageContentType.UserCard);
        this.cardType = cardType;
        this.target = target;
        this.displayName = displayName;
        this.portrait = portrait;
        this.from = from;
    }

    override encode(): MessagePayload {
        const payload = super.encode()
        payload.content = this.target;
        const obj = {
            t: this.cardType,
            n: this.name,
            d: this.displayName,
            p: this.portrait,
            f: this.from,
        } as UTSJSONObject;
        payload.binaryContent = utf8_to_b64(JSON.stringify(obj)!);
        return payload;
    }

    override decode(payload: MessagePayload): void {
        super.decode(payload)
        this.target = payload.content;
        const obj = JSON.parseObject(b64_to_utf8(payload.binaryContent));
        if (obj != null) {
            this.cardType = obj.getNumber('t') ?? 0;
            this.name = obj.getString('n') ?? '';
            this.displayName = obj.getString('d') ?? '';
            this.portrait = Config.urlRedirect(obj.getString('p') ?? '');
            this.from = obj.getString('f') ?? '';
        }
    }

    override digest(message: any | null): string {
        let msg = '[名片]';
        switch (this.cardType) {
            case 0:
                msg = '[个人名片]'
                break;
            case 1:
                msg = '[群组名片]'
                break;
            case 2:
                msg = '[聊天室名]'
                break;
            case 3:
                msg = '[频道名片]'
                break;
            default:
                break;
        }
        return msg + this.displayName;
    }
}
