/*
 * Copyright (c) 2020 WildFireChat. All rights reserved.
 */

import MessageContentType from './messageContentType.uts';
import TextMessageContent from './textMessageContent.uts';

export default class PTextMessageContent extends TextMessageContent {
    constructor(content: string, mentionedType: number = 0, mentionedTargets: string[] = []) {
        super(content, mentionedType, mentionedTargets);
        this.type = MessageContentType.P_Text;
    }
}
