/*
 * Copyright (c) 2020 WildFireChat. All rights reserved.
 */

import MediaMessageContent from './mediaMessageContent.uts'
import MessageContentMediaType from './messageContentMediaType.uts';
import MessageContentType from './messageContentType.uts';
import MessagePayload from './messagePayload.uts';

export default class SoundMessageContent extends MediaMessageContent {
    duration = 0;

    // ---- UI 层补丁字段 ----
    _isPlaying = false;

    constructor(fileOrLocalPath: string = '', remotePath: string = '', duration: number = 0) {
        super(MessageContentType.Voice, MessageContentMediaType.Voice, fileOrLocalPath, remotePath);
        this.duration = duration;
    }

    override digest(message: any | null): string {
        return '[语音]';
    }

    override encode(): MessagePayload {
        const payload = super.encode();
        payload.mediaType = MessageContentMediaType.Voice;
        const obj = {
            duration: this.duration,
        } as UTSJSONObject;
        payload.content = JSON.stringify(obj)!;
        return payload;
    }

    override decode(payload: MessagePayload): void {
        super.decode(payload);
        if (payload.content != '') {
            const obj = JSON.parseObject(payload.content);
            if (obj != null) {
                this.duration = obj.getNumber('duration') ?? 0;
            }
        }
    }
}
